import json
import os
import sys
import time
from dataclasses import asdict, dataclass
from collections import Counter
from math import erfc, sqrt
import math

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core.chaos.nihde import NIHDE, RUST_CORE_AVAILABLE
from core.pqc.kyber768 import Kyber768


@dataclass
class ValidationReport:
    timestamp: str
    python_version: str
    rust_core_available: bool
    core_type: str
    sample_bytes: int
    entropy_bits_per_byte: float
    monobit_p_value: float
    chi_square_p_value: float
    lag1_autocorr: float
    kem_trials: int
    kem_success_rate: float
    status: str


def shannon_entropy(byte_array) -> float:
    n = len(byte_array)
    if n == 0:
        return 0.0
    counts = Counter(byte_array)
    entropy = 0.0
    for count in counts.values():
        p = count / n
        entropy -= p * math.log2(p)
    return float(entropy)


def monobit_test(bits) -> float:
    ones = sum(bits)
    n = len(bits)
    if n == 0:
        return 0.0

    # Normal approximation fallback
    s_obs = abs(2 * ones - n) / sqrt(n)
    return float(erfc(s_obs / sqrt(2)))


def chi_square_uniform_test(byte_array: list[int]) -> float:
    n = len(byte_array)
    if n == 0:
        return 0.0
    counts = [0] * 256
    for b in byte_array:
        counts[b] += 1

    expected = n / 256
    chi2 = sum((c - expected) ** 2 / expected for c in counts)

    # Wilson-Hilferty normal approximation for p-value (df=255)
    k = 255.0
    z = ((chi2 / k) ** (1 / 3) - (1 - 2 / (9 * k))) / sqrt(2 / (9 * k))
    # upper tail for standard normal
    return float(0.5 * erfc(z / sqrt(2)))


def lag1_autocorrelation(byte_array: list[int]) -> float:
    if len(byte_array) < 2:
        return 0.0
    x = byte_array[:-1]
    y = byte_array[1:]
    x_mean = sum(x) / len(x)
    y_mean = sum(y) / len(y)
    num = sum((a - x_mean) * (b - y_mean) for a, b in zip(x, y))
    den_x = sum((a - x_mean) ** 2 for a in x)
    den_y = sum((b - y_mean) ** 2 for b in y)
    den = sqrt(den_x * den_y)
    if den == 0:
        return 0.0
    return float(num / den)


def validate_kem_consistency(trials: int = 200) -> float:
    success = 0
    for _ in range(trials):
        pk, sk = Kyber768.keygen()
        ss_enc, ct = Kyber768.encaps(pk)
        ss_dec = Kyber768.decaps(sk, ct)
        if ss_enc == ss_dec:
            success += 1
    return success / trials if trials > 0 else 0.0


def run_independent_validation(sample_bytes: int = 200_000, kem_trials: int = 200) -> ValidationReport:
    engine = NIHDE(use_live_qrng=False)

    start = time.perf_counter()
    data = [engine.decide() for _ in range(sample_bytes)]
    elapsed = time.perf_counter() - start

    bits = []
    for byte in data:
        for shift in range(7, -1, -1):
            bits.append((byte >> shift) & 1)

    entropy = shannon_entropy(data)
    monobit_p = monobit_test(bits)
    chi_p = chi_square_uniform_test(data)
    acf1 = lag1_autocorrelation(data)
    kem_rate = validate_kem_consistency(trials=kem_trials)

    status = "PASS"
    if monobit_p <= 0.01 or chi_p <= 0.01 or kem_rate < 1.0:
        status = "REVIEW"

    print("=" * 80)
    print("ENTROPYHUB INDEPENDENT VALIDATION")
    print("=" * 80)
    print(f"Generated bytes      : {sample_bytes:,}")
    print(f"Generation time      : {elapsed:.3f} s")
    print(f"Entropy (bits/byte)  : {entropy:.6f}")
    print(f"Monobit p-value      : {monobit_p:.6f}")
    print(f"Chi-square p-value   : {chi_p:.6f}")
    print(f"Lag-1 autocorr       : {acf1:.6f}")
    print(f"KEM success rate     : {kem_rate * 100:.2f}% ({kem_trials} trials)")
    print(f"Validation status    : {status}")

    return ValidationReport(
        timestamp=time.strftime("%Y-%m-%d %H:%M:%S"),
        python_version=sys.version,
        rust_core_available=bool(RUST_CORE_AVAILABLE),
        core_type=type(engine.core).__name__,
        sample_bytes=sample_bytes,
        entropy_bits_per_byte=entropy,
        monobit_p_value=monobit_p,
        chi_square_p_value=chi_p,
        lag1_autocorr=acf1,
        kem_trials=kem_trials,
        kem_success_rate=kem_rate,
        status=status,
    )


if __name__ == "__main__":
    report = run_independent_validation()
    out_dir = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), "docs", "verification")
    os.makedirs(out_dir, exist_ok=True)
    out_file = os.path.join(out_dir, "independent_validation_report.json")
    with open(out_file, "w", encoding="utf-8") as f:
        json.dump(asdict(report), f, indent=2)
    print(f"Saved report: {out_file}")
